apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-datagen
  name: ksql-datagen
  namespace: kafka

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksql-datagen
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/confluent-all-in-one-default: "true"
        io.kompose.service: ksql-datagen
    spec:
      containers:
        - args:
            - bash
            - -c
            - echo Waiting for Kafka to be ready... && cub kafka-ready -b broker.kafka.svc.cluster.local:29092 1 40 && echo Waiting for Confluent Schema Registry to be ready... && cub sr-ready schema-registry-service.default.svc.cluster.local 8081 40 && echo Waiting a few seconds for topic creation to finish... && sleep 11 && tail -f /dev/null
          env:
            - name: KSQL_CONFIG_DIR
              value: /etc/ksql
            - name: STREAMS_BOOTSTRAP_SERVERS
              value: broker.kafka.svc.cluster.local:29092
            - name: STREAMS_SCHEMA_REGISTRY_HOST
              value: schema-registry-service.kafka.svc.cluster.local
            - name: STREAMS_SCHEMA_REGISTRY_PORT
              value: "8081"
          image: confluentinc/ksqldb-examples:7.5.0
          name: ksql-datagen
          resources: {}
      hostname: ksql-datagen
      restartPolicy: Always
status: {}
